# Generated by Django 3.2.25 on 2024-06-17 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_document_docfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_type', models.CharField(choices=[('Lab1', 'X'), ('Lab2', 'Y'), ('Lab3', 'Z')], default='Lab1', max_length=25)),
            ],
        ),
    ]
