# Generated by Django 3.2.25 on 2024-06-17 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_lab'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='lab_type',
            field=models.CharField(choices=[('Lab1', 'X'), ('Lab2', 'Y'), ('Lab3', 'Z')], default='Lab1', max_length=25),
        ),
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.FileField(upload_to=''),
        ),
    ]
