# Generated by Django 3.2.25 on 2024-11-13 14:31

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20240617_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.DeleteModel(
            name='Lab',
        ),
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.FileField(upload_to=myapp.models.upload_location),
        ),
        migrations.AlterField(
            model_name='document',
            name='lab_type',
            field=models.CharField(max_length=25),
        ),
    ]
