# Generated by Django 3.2.25 on 2024-12-10 10:13

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_onetimecode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimecode',
            name='code',
            field=encrypted_model_fields.fields.EncryptedCharField(unique=True),
        ),
    ]
